<a href="https://colab.research.google.com/github/sakshijadhav-08/data-exploration-and-cleaning/blob/main/Extra_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [7]:
from google.colab import files
uploaded = files.upload()

Saving Charater_Set.csv to Charater_Set (1).csv

In [8]:
filepath = '/content/Charater_Set.csv'
df = pd.read_csv(filepath)
df

,SNO,Name,House,Role,Notable Traits,Birthdate,Blood Status,Patronus,Wand Core
0,1,Harry Potter,Gryffindor,Main Protagonist,"Courageous, Loyal","July 31, 1980",Half-Blood,Stag,"Holly, 11"""
1,2,Hermione Granger,Gryffindor,Main Protagonist,"Intelligent, Brave","September 19, 1979",Muggle-born,Otter,"Vine, 10¾"""
2,3,Ron Weasley,Gryffindor,Main Protagonist,"Loyal, Funny","March 1, 1980",Pure-blood,Jack Russell Terrier,"Willow, 14"""
3,4,Draco Malfoy,Slytherin,Antagonist,"Ambitious, Proud, Arrogant","June 5, 1980",Pure-blood,Unknown,"Elm, 10"""
4,5,Albus Dumbledore,Gryffindor,Headmaster,"Wise, Kind, Compassionate",1881,Half-blood,Phoenix,"Elder, 15"""
...,...,...,...,...,...,...,...,...,...
119,120,Hermes,NaN,Percy's Owl,"Loyal, Intelligent",Unknown,Unknown,Unknown,Unknown
120,121,Pigwidgeon,NaN,Ron's Owl,"Energetic, Loyal, Mischievous",1995,Unknown,Unknown,Unknown
121,122,Hagrid's Half-brother (Grawp),NaN,"Giant, Hagrid's Relative","Large, Innocent, Loyal",Unknown,Unknown,Unknown,Unknown
122,123,Cornelius Fudge,NaN,Former Minister for Magic,"Stubborn, Incompetent",1920s,Pure-blood,Unknown,Unknown
123,124,Rufus Scrimgeour,NaN,Former Minister for Magic,"Brave, Loyal, Stern",1940s,Pure-blood,Unknown,Unknown

In [9]:
df.head(3)

,SNO,Name,House,Role,Notable Traits,Birthdate,Blood Status,Patronus,Wand Core
0,1,Harry Potter,Gryffindor,Main Protagonist,"Courageous, Loyal","July 31, 1980",Half-Blood,Stag,"Holly, 11"""
1,2,Hermione Granger,Gryffindor,Main Protagonist,"Intelligent, Brave","September 19, 1979",Muggle-born,Otter,"Vine, 10¾"""
2,3,Ron Weasley,Gryffindor,Main Protagonist,"Loyal, Funny","March 1, 1980",Pure-blood,Jack Russell Terrier,"Willow, 14"""

In [10]:
df.tail()

,SNO,Name,House,Role,Notable Traits,Birthdate,Blood Status,Patronus,Wand Core
119,120,Hermes,NaN,Percy's Owl,"Loyal, Intelligent",Unknown,Unknown,Unknown,Unknown
120,121,Pigwidgeon,NaN,Ron's Owl,"Energetic, Loyal, Mischievous",1995,Unknown,Unknown,Unknown
121,122,Hagrid's Half-brother (Grawp),NaN,"Giant, Hagrid's Relative","Large, Innocent, Loyal",Unknown,Unknown,Unknown,Unknown
122,123,Cornelius Fudge,NaN,Former Minister for Magic,"Stubborn, Incompetent",1920s,Pure-blood,Unknown,Unknown
123,124,Rufus Scrimgeour,NaN,Former Minister for Magic,"Brave, Loyal, Stern",1940s,Pure-blood,Unknown,Unknown

In [11]:
df.shape

(124, 9)

In [12]:
df.columns

Index(['SNO', 'Name', 'House', 'Role', 'Notable Traits', 'Birthdate',
       'Blood Status', 'Patronus', 'Wand Core'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SNO             124 non-null    int64
 1   Name            124 non-null    object
 2   House           97 non-null     object
 3   Role            124 non-null    object
 4   Notable Traits  124 non-null    object
 5   Birthdate       124 non-null    object
 6   Blood Status    123 non-null    object
 7   Patronus        124 non-null    object
 8   Wand Core       124 non-null    object
dtypes: int64(1), object(8)
memory usage: 8.8+ KB

In [14]:
df.describe()

              SNO
count  124.000000
mean    62.500000
std     35.939764
min      1.000000
25%     31.750000
50%     62.500000
75%     93.250000
max    124.000000

In [16]:
df.dtypes

SNO                int64
Name              object
House             object
Role              object
Notable Traits    object
Birthdate         object
Blood Status      object
Patronus          object
Wand Core         object
dtype: object

In [17]:
df.nunique()

SNO               124
Name              124
House               7
Role              103
Notable Traits    117
Birthdate          66
Blood Status        8
Patronus           20
Wand Core          14
dtype: int64

In [18]:
df.isnull().sum()

SNO                0
Name               0
House             27
Role               0
Notable Traits     0
Birthdate          0
Blood Status       1
Patronus           0
Wand Core          0
dtype: int64

In [19]:
df.sample(10)

,SNO,Name,House,Role,Notable Traits,Birthdate,Blood Status,Patronus,Wand Core
69,70,Fat Friar,Hufflepuff,"Ghost, Hufflepuff House","Jolly, Kind-hearted, Loyal",10th Century,Muggle-born,Unknown,Unknown
122,123,Cornelius Fudge,NaN,Former Minister for Magic,"Stubborn, Incompetent",1920s,Pure-blood,Unknown,Unknown
96,97,Katie Bell,Gryffindor,Quidditch Player,"Loyal, Determined",1979,Muggle-born,Unknown,Unknown
97,98,Angelina Johnson,Gryffindor,Quidditch Player,"Brave, Determined",1979,Muggle-born,Unknown,Unknown
32,33,Aberforth Dumbledore,Gryffindor,"Barman, Brother of Albus","Private, Protective, Loyal",1884,Half-blood,Goat,Unknown
39,40,Nymphadora Tonks,Gryffindor,"Auror, Metamorphmagus","Kind, Quirky, Brave",1973,Half-blood,Patronus - Otter,"Willow, 10½"""
70,71,The Bloody Baron,Slytherin,"Ghost, Slytherin House","Brooding, Tragic, Mournful",15th Century,Pure-blood,Unknown,Unknown
54,55,Dudley Dursley,NaN,Harry’s Cousin,"Spoiled, Bully, Self-centered","June 23, 1980",Muggle-born,Unknown,Unknown
118,119,Hedwig,NaN,Harry's Owl,"Loyal, Protective, Intelligent",1991,Unknown,Unknown,Unknown
6,7,Minerva McGonagall,Gryffindor,Transfiguration Professor,"Stern, Fair, Powerful","October 4, 1935",Muggle-born,Tabby Cat,"Fir, 9½"""

In [20]:
df.value_counts()

SNO  Name                                                     House       Role                       Notable Traits                    Birthdate           Blood Status  Patronus              Wand Core
1    Harry Potter                                             Gryffindor  Main Protagonist           Courageous, Loyal                 July 31, 1980       Half-Blood    Stag                  Holly, 11"     1
2    Hermione Granger                                         Gryffindor  Main Protagonist           Intelligent, Brave                September 19, 1979  Muggle-born   Otter                 Vine, 10¾"     1
3    Ron Weasley                                              Gryffindor  Main Protagonist           Loyal, Funny                      March 1, 1980       Pure-blood    Jack Russell Terrier  Willow, 14"    1
4    Draco Malfoy                                             Slytherin   Antagonist                 Ambitious, Proud, Arrogant        June 5, 1980        Pure-blood    Unknown               Elm, 10"       1
5    Albus Dumbledore                                         Gryffindor  Headmaster                 Wise, Kind, Compassionate         1881                Half-blood    Phoenix               Elder, 15"     1
                                                                                                                                                                                                             ..
108  Ernie Macmillan                                          Hufflepuff  Student                    Loyal, Honest, Hardworking        1979                Muggle-born   Unknown               Unknown        1
109  Justin Finch-Fletchley                                   Hufflepuff  Student                    Kind, Curious, Supportive         1980                Muggle-born   Unknown               Unknown        1
110  Nearly Headless Nick (Sir Nicholas de Mimsy-Porpington)  Gryffindor  Ghost of Gryffindor House  Polite, Honorable, Humorous       1500s               Pure-blood    Unknown               Unknown        1
111  The Fat Friar                                            Hufflepuff  Ghost of Hufflepuff House  Kind-hearted, Cheerful, Generous  1000s               Unknown       Unknown               Unknown        1
112  Moaning Myrtle                                           Ravenclaw   Ghost of Girls' Bathroom   Whiny, Sensitive, Mischievous     1920s               Half-blood    Unknown               Unknown        1
Name: count, Length: 97, dtype: int64